# Generated by Django 2.0.6 on 2019-02-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='accountBalance',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='accountNumber',
            field=models.IntegerField(),
        ),
    ]
