# Generated by Django 2.0.6 on 2019-02-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_auto_20190220_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountBalance',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
    ]
